### ISSUE TITLE
Fatal error after activaiting

### ISSUE THREAD

**Issue by timscha** [wp-statistics/wp-statistics#356]
After activaiting, I got an mail from Wordpress with an error message.
I got this messge also, when I look arround "Schedule weekly update of Matomo Referrer Spam Blacklist DB:"

Also nothing happens when I click on Maintenance and Reset and About, the plugin does not display something.

Error message:
`Error Details
=============
An error of type E_ERROR was caused in line 198 of the file /var/www/vhosts/timscharner.com/public/wp-content/plugins/wp-statistics/includes/admin/templates/settings/externals.php. Error message: Uncaught TypeError: Unsupported operand types: string + int in /var/www/vhosts/timscharner.com/public/wp-content/plugins/wp-statistics/includes/admin/templates/settings/externals.php:198
Stack trace:
#0 /var/www/vhosts/timscharner.com/public/wp-content/plugins/wp-statistics/includes/admin/templates/settings.php(50): include()
#1 /var/www/vhosts/timscharner.com/public/wp-content/plugins/wp-statistics/includes/admin/class-wp-statistics-admin-template.php(72): include('...')
#2 /var/www/vhosts/timscharner.com/public/wp-content/plugins/wp-statistics/includes/admin/pages/class-wp-statistics-admin-page-settings.php(61): WP_STATISTICS\Admin_Template::get_template()
#3 /var/www/vhosts/timscharner.com/public/wp-includes/class-wp-hook.php(292): WP_STATISTICS\settings_page::view()
#4 /var/www/vhosts/timscharner.com/public/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#5 /var/www/vhosts/timscharner.com/public/wp-includes/plugin.php(484): WP_Hook->do_action()
#6 /var/www/vhosts/timscharner.com/public/wp-admin/admin.php(259): do_action()
#7 {main}
 thrown`

I am using nginx, MariaDB 10.5 and PHP 8.0.

**Comment by mostafasoufi** [comment]
Hey,

Thank you for reporting the bug, the issue has been fixed in this commit https://github.com/wp-statistics/wp-statistics/commit/ce96397f5db982fdbf89d75ecaaf4d1815fe9b2e, you can fix this manually or install the dev version until the new version released.
https://github.com/wp-statistics/wp-statistics/archive/refs/heads/development.zip

Best
