### ISSUE TITLE
Blank Full Site Editor

### ISSUE THREAD

**Issue by Pulsar-X** [wp-statistics/wp-statistics#443]
WordPress Version: 6.3.2
WP Statistics Version: 14.2

When I enter the Full Site Editor, I just get a blank, white page. The Browser console reveals that the server answers with a 500: Internal server Error.

Checking the logs, I get this:
```
[07-Nov-2023 11:04:08 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE" in /html/wordpress/wp-includes/pluggable.php:929
Stack trace:
#0 /html/wordpress/wp-includes/pluggable.php(694): wp_parse_auth_cookie(false, '')
#1 /html/wordpress/wp-includes/class-wp-hook.php(310): wp_validate_auth_cookie(false)
#2 /html/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#3 /html/wordpress/wp-includes/user.php(3622): apply_filters('...', false)
#4 /html/wordpress/wp-includes/pluggable.php(70): _wp_get_current_user()
#5 /html/wordpress/wp-includes/l10n.php(98): wp_get_current_user()
#6 /html/wordpress/wp-includes/l10n.php(152): get_user_locale()
#7 /html/wordpress/wp-includes/l10n.php(947): determine_locale()
#8 /html/wordpress/wp-admin/includes/plugin.php(148): load_plugin_textdomain('...', false, '...')
#9 /html/wordpress/wp-admin/includes/plugin.php(111): _get_plugin_data_markup_translate('...', Array, true, true)
#10 /html/wordpress/wp-content/plugins/wp-statistics/includes/defines.php(16): get_plugin_data('...')
#11 /html/wordpress/wp-content/plugins/wp-statistics/wp-statistics.php(17): require_once('...')
#12 /html/wordpress/wp-settings.php(407): include_once('...')
#13 /html/wordpress/wp-config.php(130): require_once('...')
#14 /html/wordpress/wp-load.php(50): require_once('...')
#15 /html/wordpress/wp-admin/admin.php(34): require_once('...')
#16 /html/wordpress/wp-admin/site-editor.php(12): require_once('...')
#17 {main}
  thrown in /html/wordpress/wp-includes/pluggable.php on line 929
[07-Nov-2023 11:04:08 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE" in /html/wordpress/wp-includes/pluggable.php:929
Stack trace:
#0 /html/wordpress/wp-includes/pluggable.php(694): wp_parse_auth_cookie(false, '')
#1 /html/wordpress/wp-includes/class-wp-hook.php(310): wp_validate_auth_cookie(false)
#2 /html/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#3 /html/wordpress/wp-includes/user.php(3622): apply_filters('...', false)
#4 /html/wordpress/wp-includes/pluggable.php(70): _wp_get_current_user()
#5 /html/wordpress/wp-includes/l10n.php(98): wp_get_current_user()
#6 /html/wordpress/wp-includes/l10n.php(152): get_user_locale()
#7 /html/wordpress/wp-includes/l10n.php(894): determine_locale()
#8 /html/wordpress/wp-includes/class-wp-fatal-error-handler.php(47): load_default_textdomain()
#9 [internal function]: WP_Fatal_Error_Handler->handle()
#10 {main}
  thrown in /html/wordpress/wp-includes/pluggable.php on line 929
```

Weirdly, I get this Error when I have both WP Statistics and W3 Total Cache activated, or just either one of them.

I have reported this to W3 Total Cache too ( https://github.com/BoldGrid/w3-total-cache/issues/766 ), but since I also get this error when I just have WP Statistics activated, it might just be a coincidence that both Plugins have the same issue.

**Comment by mostafasoufi** [comment]
Hey,

The Undefined constant `SECURE_AUTH_COOKIE` issue broadly speaking suggests that a plugin or mu-plugin is loading a core WordPress file out of order. I'd prefer to load `wp-includes/pluggable.php` in advance.

Adding this hook on `functions.php` of the theme should probably fix the issue

```
add_action('init', function () {
    include_once(ABSPATH . 'wp-includes/pluggable.php');
});
```

Or:

```
add_action('after_setup_theme', function () {
    include_once(ABSPATH . 'wp-includes/pluggable.php');
});
```

**Comment by mostafasoufi** [comment]
Still the same issue? can you please check the latest PHP error?

**Comment by Pulsar-X** [comment]
It seems to be exactly the same error. This is with
```php
add_action('after_setup_theme', function () {
    include_once(ABSPATH . 'wp-includes/pluggable.php');
});
```
in my themes `functions.php`:

```
[28-Nov-2023 15:41:59 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE" in /html/wordpress/wp-includes/pluggable.php:929
Stack trace:
#0 /html/wordpress/wp-includes/pluggable.php(694): wp_parse_auth_cookie(false, '')
#1 /html/wordpress/wp-includes/class-wp-hook.php(324): wp_validate_auth_cookie(false)
#2 /html/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#3 /html/wordpress/wp-includes/user.php(3628): apply_filters('...', false)
#4 /html/wordpress/wp-includes/pluggable.php(70): _wp_get_current_user()
#5 /html/wordpress/wp-includes/l10n.php(98): wp_get_current_user()
#6 /html/wordpress/wp-includes/l10n.php(152): get_user_locale()
#7 /html/wordpress/wp-includes/l10n.php(947): determine_locale()
#8 /html/wordpress/wp-admin/includes/plugin.php(148): load_plugin_textdomain('...', false, '...')
#9 /html/wordpress/wp-admin/includes/plugin.php(111): _get_plugin_data_markup_translate('...', Array, true, true)
#10 /html/wordpress/wp-content/plugins/wp-statistics/includes/defines.php(16): get_plugin_data('...')
#11 /html/wordpress/wp-content/plugins/wp-statistics/wp-statistics.php(17): require_once('...')
#12 /html/wordpress/wp-settings.php(418): include_once('...')
#13 /html/wordpress/wp-config.php(132): require_once('...')
#14 /html/wordpress/wp-load.php(50): require_once('...')
#15 /html/wordpress/wp-admin/admin.php(34): require_once('...')
#16 /html/wordpress/wp-admin/site-editor.php(12): require_once('...')
#17 {main}
  thrown in /html/wordpress/wp-includes/pluggable.php on line 929
[28-Nov-2023 15:41:59 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE" in /html/wordpress/wp-includes/pluggable.php:929
Stack trace:
#0 /html/wordpress/wp-includes/pluggable.php(694): wp_parse_auth_cookie(false, '')
#1 /html/wordpress/wp-includes/class-wp-hook.php(324): wp_validate_auth_cookie(false)
#2 /html/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#3 /html/wordpress/wp-includes/user.php(3628): apply_filters('...', false)
#4 /html/wordpress/wp-includes/pluggable.php(70): _wp_get_current_user()
#5 /html/wordpress/wp-includes/l10n.php(98): wp_get_current_user()
#6 /html/wordpress/wp-includes/l10n.php(152): get_user_locale()
#7 /html/wordpress/wp-includes/l10n.php(894): determine_locale()
#8 /html/wordpress/wp-includes/class-wp-fatal-error-handler.php(47): load_default_textdomain()
#9 [internal function]: WP_Fatal_Error_Handler->handle()
#10 {main}
  thrown in /html/wordpress/wp-includes/pluggable.php on line 929
```

If you have any ideas how I could help with narrowing down the issue more, please let me know.

**Comment by mostafasoufi** [comment]
Can you also please tell me what is your PHP version?
