### ISSUE TITLE
Uncaught mysqli_sql_exception for WP_STATISTICS\Install::create_events_table() on upgrade 14.1 -> 14.7

### ISSUE THREAD

**Issue by Thomas-1985** [wp-statistics/wp-statistics#490]
Hello,

I wanted to upgrade from 14.1 to 14.7 but got the following error in my webserver log (i had to revert back to 14.1)

```
2024-05-26 11:03:49	Error	92.116.184.246		19657#0: *2677047 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF' at line 1 in /var/www/vhosts/mysite/httpdocs/wp-includes/wp-db.php:2056
Stack trace:
#0 /var/www/vhosts/mysite/httpdocs/wp-includes/wp-db.php(2056): mysqli_query()
#1 /var/www/vhosts/mysite/httpdocs/wp-includes/wp-db.php(1945): wpdb->_do_query()
#2 /var/www/vhosts/mysite/httpdocs/wp-includes/wp-db.php(2695): wpdb->query()
#3 /var/www/vhosts/mysite/httpdocs/wp-admin/includes/upgrade.php(2749): wpdb->get_results()
#4 /var/www/vhosts/mysite/httpdocs/wp-content/plugins/wp-statistics/includes/class-wp-statistics-install.php(259): dbDelta()
#5 /var/www/vhosts/mysite/httpdocs/wp-content/plugins/wp-statistics/includes/class-wp-statistics-install.php(515): WP_STATISTICS\Install::create_events_table()
#6 /var/www/vhosts/mysite/httpdocs/wp-includes/class-wp-hook.php(303): WP_STATISTICS\Install" while reading response header from upstream
```

Then i tried to remove the plugin and install it again. However it could not be activated due to the following error
```
Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF' at line 1 in /var/www/vhosts/mysite/httpdocs/wp-includes/wp-db.php:2056 Stack trace: #0 /var/www/vhosts/mysite/httpdocs/wp-includes/wp-db.php(2056): mysqli_query() #1 /var/www/vhosts/mysite/httpdocs/wp-includes/wp-db.php(1945): wpdb->_do_query() #2 /var/www/vhosts/mysite/httpdocs/wp-includes/wp-db.php(2695): wpdb->query() #3 /var/www/vhosts/mysite/httpdocs/wp-admin/includes/upgrade.php(2749): wpdb->get_results() #4 /var/www/vhosts/mysite/httpdocs/wp-content/plugins/wp-statistics/includes/class-wp-statistics-install.php(259): dbDelta() #5 /var/www/vhosts/mysite/httpdocs/wp-content/plugins/wp-statistics/includes/class-wp-statistics-install.php(208): WP_STATISTICS\Install::create_events_table() #6 /var/www/vhosts/mysite/httpdocs/wp-content/plugins/wp-statistics/includes/class-wp-statistics-install.php(63): WP_STATISTICS\Install::table_sql() #7 /var/www/vhosts/mysite/httpdocs/wp-content/plugins/wp-statistics/includes/class-wp-statistics-install.php(35): WP_STATISTICS\Install::create_table() #8 /var/www/vhosts/mysite/httpdocs/wp-content/plugins/wp-statistics/includes/class-wp-statistics.php(325): WP_STATISTICS\Install->install() #9 /var/www/vhosts/mysite/httpdocs/wp-includes/class-wp-hook.php(303): WP_Statistics::install() #10 /var/www/vhosts/mysite/httpdocs/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #11 /var/www/vhosts/mysite/httpdocs/wp-includes/plugin.php(470): WP_Hook->do_action() #12 /var/www/vhosts/mysite/httpdocs/wp-admin/plugins.php(193): do_action() #13 {main} thrown in /var/www/vhosts/mysite/httpdocs/wp-includes/wp-db.php on line 2056
```

How can i fix that?

Best,
Thomas

**Comment by mostafasoufi** [comment]
Hello,

Thank you for reporting the issue. We have fixed it in commit 5c7b05d4b4ed5a16a79185143068b9f8d52f6200, and a minor release will be available soon.
